version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./insightface_data:/models
      - ./data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
