version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app  # Mount backend code directory to container
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app  # Mount frontend code directory to container
      - /app/node_modules  # Prevent overriding node_modules with host directory
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
