version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./insightface_data:/tmp/insightface/models/buffalo_l
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
