version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app                # Mount backend code for live reload
      - ./insightface_data:/models    # Mount model data for InsightFace
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    restart: always